#define SERIAL_BAUD_RATE 9600
#define SERIAL_INPUT_BUFFER_SIZE 100
#define MAX_NUM_POINTS_FOR_ROUTINE 30
#define SERIAL_OUTPUT_INTERVAL 2000
#define DISPLAY_INTERVAL 2000
#define CURRENT_PIN A0
#define TENSION_PIN A1
#define DISPLAY_PIN_RS 7
#define DISPLAY_PIN_EN 8
#define DISPLAY_PIN_D4 9
#define DISPLAY_PIN_D5 10
#define DISPLAY_PIN_D6 11
#define DISPLAY_PIN_D7 12

// #define DEBUG_LOOP_DELAY 5000
// #define DEBUG_SHOW_RAM
// #define DEBUG_PRINT_ROUTINE
// #define DEBUG_DISABLE_METRICS
// #define DEBUG_VERBOSE_METRICS
// #define DEBUG_PRINT_POINT_ADDED